version: "1.0"
info:
  model: int-scaffold
packages:
- name: InventoryOrderManagementProject
  gitServerName: OrderManagementRepo
  gitUrl: https://github.com/bharathreddy89
  gitUsername: bharathreddy89
  gitBranch: main
- name: DeliveryPartner
  gitServerName: OrderManagementRepo
  gitUrl: https://github.com/bharathreddy89
  gitUsername: bharathreddy89
  gitBranch: main
- name: OrderHistory
  gitServerName: OrderManagementRepo
  gitUrl: https://github.com/bharathreddy89
  gitUsername: bharathreddy89
  gitBranch: main
